### ISSUE TITLE
Verbrauchsanzeige totalmonthnow andere Werte als in App

### ISSUE THREAD

**Issue by Rawx17** [arteck/ioBroker.hs100#100]
Hallo

Wie in der Überschrift erwähnt, wird in der App ein anderer Wert angezeigt als im iobroker.
In App letzte 30 tage: 5,78kWh
In iobroker totalMonthnow: 3,843kWh
Ich habe eine tp link kp115 dose.

Muss ich irgendwas beachten oder wie kann so ein unterschied zustande kommen? Liegt es daran dass in iobroker tatsächlich der monat genommen wird und nicht die letzten 30 Tage? oder weil ich die steckdose schon am laufen hatte ohne sie in iobroker eingebunden zu haben?

Wäre froh über infos!
Sollte noch infos meinerseits benötigt werden reiche ich diese gerne nach!

Danke!

Weitere infos:
adapter version 2.0.6 
js controller 3.3.18
Node.js v14.17.5
NPM 6.14.14
OS win10

**Comment by arteck** [comment]
der Adapter fragt die Daten der Dose app.. ergo wenn da was nicht passt dann liefert die Dose andere werte..was die app macht .. ob da irgendwelche summen laufen.. habe ich nicht analysiert
