### ISSUE TITLE
Continuesly Warning "getDevice Socket connection Timeout ip: 192.168.xxx.xx please reconnect the Device"

### ISSUE THREAD

**Issue by marian-t-web-de** [arteck/ioBroker.hs100#114]
Hello @arteck 

it is not a bug, but maybe a suggestion for improvement.

When hs100 device or repeater failed, produces the ioBroker.hs100 module every 10 sec a warning in log, in my case 2 weeks long (holiday). 

Could You pls. change it and make the warning optional, for instance in ioBroker instance settings? 
Or limit the quantity to n warnings for each IP?

![image](https://user-images.githubusercontent.com/37208979/155679134-d3194ff0-a209-4277-bd8f-4815323a654a.png)

regards
marian.t

**Comment by arteck** [comment]
hmm..the problem is.. you are back und look into the LOG.. what can you see.. 
ahh all is fine no warnings.. 
i think 10 sec pollintervall is also very poor

**Comment by marian-t-web-de** [comment]
Hello artec,

one warning is fine, but in two weeks I'v got about 130.000 warnings - the Idea was to reduce the quantity of them in such case.

**Comment by arteck** [comment]
one warning is fine.. 
how often?? day, week, year.. its for you maybe better but nor for all user

so check this brunch 

https://github.com/arteck/ioBroker.hs100/tree/warning-off


you can set OFF ALL WARN connect Massages
![grafik](https://user-images.githubusercontent.com/6681528/156506122-b661030b-6fe8-484b-be54-bfc3d6a08fe0.png)
