### ISSUE TITLE
Warnmeldungen in den Protokollen

### ISSUE THREAD

**Issue by weindler** [arteck/ioBroker.hs100#122]
Hallo,

folgende Warnmeldungen erhalte ich für den HS 100 Adapter
`<html><body>

hs100.0 | 2022-03-09 17:36:06.057 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
hs100.0 | 2022-03-09 17:36:06.056 | warn | Object 192_168_178_XX.ledState is invalid: Default value has to be type "string" but received type "boolean"
hs100.0 | 2022-03-09 17:36:06.054 | warn | This object will not be created in future versions. Please report this to the developer.
hs100.0 | 2022-03-09 17:36:06.052 | warn | Object 192_168_178_XX.last_update is invalid: Default value has to be type "string" but received type "number"

</body>
</html>`

Plattform
    linux
Betriebssystem
    linux
Architektur
    arm
CPUs
    4
Geschwindigkeit
    1500 MHz
Modell
    ARMv7 Processor rev 3 (v7l)
RAM
    3.8 GB
System-Betriebszeit
    00:09:30
Node.js
    v14.19.0
time
    1646844221693
timeOffset
    -60
Anzahl der Adapter
    400
NPM
    6.14.16
js-controller
    4.0.19

**Comment by neunteufels** [comment]
Hallo,

bekomme die gleichen Meldungen.

lg

**Comment by arteck** [comment]
https://github.com/arteck/ioBroker.hs100/issues/115#event-6171734884
