### ISSUE TITLE
Object [IP].last_update is invalid: Default value has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by JensReitemeyer** [arteck/ioBroker.hs100#123]
**Describe the bug**  
Message "Object [IP].last_update is invalid: Default value has to be type "string" but received type "number" to see in the log. Further hint: "This object will not be created in future versions. Please report this to the developer."

**To Reproduce**  
By starting the instance. Happens with 2.0.6 / 2.0.7

**Expected behavior**  
Choose right object type

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/31849278/160546298-ce733032-c100-4a98-8471-cc3f436e3d6e.png)

**Versions:**  
 - Adapter version: <adapter-version>2.0.7
 - JS-Controller version: <js-controller-version>4.0.21
 - Node version: <node-version>14.19.0
 - Operating system: <os-name>Ubuntu 18.04.6 LTS

**Additional context**  
thx in advance

**Comment by arteck** [comment]
del all the objects
restart adapter

done
