### ISSUE TITLE
Warnings since update to 2.0.7

### ISSUE THREAD

**Issue by marian-t-web-de** [arteck/ioBroker.hs100#143]
**Describe the bug**  
since update to 2.0.7 log warnings

hs100.0 | 2022-06-07 17:56:20.170 | warn | This object will not be created in future versions. Please report this to the developer.
received type "boolean"
hs100.0 | 2022-06-07 17:56:20.188 | warn | Object 192_168_178_27.last_update is invalid: Default value has to be type "string" but received type "number"

ledState value is true
last_update value is '2022.6.7 18:17:50'

After hs100.0.192_168_178_25.ledState was manually changed to boolean:
hs100.0 | 2022-06-07 17:57:21.586 | info | State value to set for "hs100.0.192_168_178_25.ledState" has to be type "boolean" but received type "string"
admin.0 | 2022-06-07 17:58:34.023 | warn | Object hs100.0.192_168_178_25.ledState is invalid: Default value has to be type "string" but 
received type "boolean"

**To Reproduce**  
1. Go to '.Logs'
2. See warnings

**Expected behavior**  
no warnings

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37208979/172428242-0bb431bd-707b-4ac3-a83d-3e7422a01d8e.png)

**Versions:**  
 - Adapter version: 2.0.7
 - JS-Controller version: 4.0.23
 - Node version: v12.22.8
 - Operating system: RaspiOS

**Additional context**  
no context

**Comment by arteck** [comment]
check new version
