### ISSUE TITLE
HS100 Adapter sometimes resets states

### ISSUE THREAD

**Issue by marian-t-web-de** [arteck/ioBroker.hs100#210]
Sometimes the HS100 Adapter resets states. 
After switching one of hs100 states manually to ON it will be set with "Anfrage intervall" back to off. It happens no more after restart of Adapter, but some time / some days later the behavior is again false.

**To Reproduce**  
1. Go to HS100 Objects
2. Click on one of HS100 switch-state and set it to ON manually
3. Wait till "Anfrage intervall" is over
4. Check the state changed in item 2 - it is OFF 
5. If logging of HS100 Adapter was switched to debug bevore, resetting of states is protocolled there.

**Expected behavior**  
The manually changed HS100 state changes itself no more

**Screenshots & Logfiles**  
After activating the debug-Log in adapter instance the state changing to off is shown in protocoll
`<html>
<body>

hs100.0 | 2023-10-02 16:19:24.415 | debug | Day value for Model : HS110(EU) Energy : 0 IP : 192.168.178.25
-- | -- | -- | --
hs100.0 | 2023-10-02 16:19:24.125 | debug | Month value Model : HS110(EU) IP : 192.168.178.25
hs100.0 | 2023-10-02 16:19:23.834 | debug | Refresh Data HS110 192.168.178.25
hs100.0 | 2023-10-02 16:19:23.544 | debug | Refresh 192.168.178.25 Model = HS110(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.422 | debug | stateID hs100.0.192_168_178_28.state changed: false (ack = true)
hs100.0 | 2023-10-02 16:19:23.352 | debug | stateID hs100.0.192_168_178_27.state changed: false (ack = true)
hs100.0 | 2023-10-02 16:19:23.343 | debug | Refresh 192.168.178.21 Model = HS100(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.342 | debug | Refresh 192.168.178.28 Model = KP105(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.339 | debug | Refresh 192.168.178.22 Model = HS100(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.325 | debug | Refresh 192.168.178.27 Model = KP105(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.323 | debug | Refresh 192.168.178.24 Model = KP105(EU) state = false update = 2023.10.2 16:19:23
hs100.0 | 2023-10-02 16:19:23.290 | debug | get Information

</body>
</html>`
**Versions:**  
 raspberrypi
Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.75 GB
System-Betriebszeit
73 T. 22:33:32
Node.js
v16.19.1 (Es gibt eine neuere Version: v16.20.2 - Empfohlene Version v18.18.0)
time
1696257718226
timeOffset
-120
Anzahl der Adapter
501
NPM
9.5.1
Datenträgergröße
28.14 GB
freier Festplattenspeicher
19.87 GB
Betriebszeit
73 T. 22:33:13
Aktive Instanzen
23
Weg
/opt/iobroker/
Hostname
raspberrypi

HS100 Adapter 2.1.2

**Additional context**  
n.a.

**Comment by arteck** [comment]
i have here 4 plugs hs100 and hs110 .. and i cant reproduce this

**Comment by marian-t-web-de** [comment]
How can You explain the hs100 Msg. in iobroker log above - are form an another Skript/Kasa?

**Comment by arteck** [comment]
i can see anything in the LOG

**Comment by marian-t-web-de** [comment]
Maybe I don't  understand the message:
"Refresh 192.168.178.27 Model = KP105(EU) state = false update = 2023.10.2 16:19:23" and 
"stateID hs100.0.192_168_178_27.state changed: false (ack = true)"

It happens shortly after setting true by the user.

I can't reproduce it now - lovelace is no more working properly after update of Node.js to 18.18.2 today.

I'll try to do it when it works again.
