### ISSUE TITLE
Adapter working fine, but keeps giving error about connection

### ISSUE THREAD

**Issue by ramizh** [arteck/ioBroker.hs100#24]
Adapter working fine I can connect to the plug, but it spams my log with this error:

hs100.0 | 2018-03-30 20:12:21.845 | info | Fehler Dose nicht erreichbar : 192.168.1.24
-- | -- | -- | --

**Comment by arteck** [comment]
install now from git..

**Comment by ramizh** [comment]
Thank you for the fast adjustment.
Unfortunately when starting the adapter, it does not go online anymore after reinstalling the latest for Git.

**Comment by arteck** [comment]
check the new version
