### ISSUE TITLE
HS110 with Hardware Version 2.0 does not work properly with the Adapter

### ISSUE THREAD

**Issue by ramizh** [arteck/ioBroker.hs100#27]
Hello!

So I had a HS110 unit for more than a month and it worked perfectly, now I bought a new one and the new unit has a different hardware version (2.0) and runs with firmware version 1.5.2.
After adding the plug to the adapter the objects are created but the most important information is not relayed and stays as "0" such as **(current, power, totalMonthNow, totalNow)**

The rest of the information such as hw_ver, last_update, mac, model, state and sw_ver is shown normally.

**Comment by arteck** [comment]
i check this...

**Comment by arteck** [comment]
update done

**Comment by ramizh** [comment]
Thanks for the time to put to fix the issues!
Unfortunately, I reinstalled the adapter and it still does not show the information. Check screenshot for an example.
![hs110_1](https://user-images.githubusercontent.com/36566465/41122125-d99cb18e-6a9a-11e8-9141-c8cbb3593188.png)
