### ISSUE TITLE
Neuer hs110 zählt nicht

### ISSUE THREAD

**Issue by Pocky2507** [arteck/ioBroker.hs100#29]
Heute einen neuen hs110 bekommen.
Der unterscheidet sich deutlich von den anderen.

Hardwareversion 2.0
Softwareversion   1.5.2 Build 180130 Rel.085820

Wird vom Adapter erkannt, aber zählt nicht.

Edit ON
Unten bei Realtime werden wohl die Werte anders ausgelesen als bei den älteren Steckern.
Edit OFF

-----------------------------------------------------------

tplink-smarthome-api getInfo 192.168.123.30
Sending getInfo command to 192.168.123.30:undefined...
response:
{ sysInfo: 
   { sw_ver: '1.5.2 Build 180130 Rel.085820',
     hw_ver: '2.0',
     type: 'IOT.SMARTPLUGSWITCH',
     model: 'HS110(EU)',
     mac: 'AC:84:C6:5D:92:B2',
     dev_name: 'Smart Wi-Fi Plug With Energy Monitoring',
     alias: 'Kraftraum',
     relay_state: 1,
     on_time: 629,
     active_mode: 'none',
     feature: 'TIM:ENE',
     updating: 0,
     icon_hash: '',
     rssi: -36,
     led_off: 0,
     longitude_i: 91082,
     latitude_i: 522430,
     hwId: '044A516EE63C875F9458DA25C2CCC5A0',
     fwId: '00000000000000000000000000000000',
     deviceId: '80064355F679D92CEDAF5D9872F703711A084D03',
     oemId: '1998A14DAA86E4E001FD7CAF42868B5E',
     next_action: { type: -1 },
     err_code: 0 },
  cloud: 
   { info: 
      { username: 'achim@xxxxx.xxxx',
        server: 'devs.tplinkcloud.com',
        binded: 1,
        cld_connection: 1,
        illegalType: 0,
        tcspStatus: 1,
        fwDlPage: '',
        tcspInfo: '',
        stopConnect: 0,
        fwNotifyType: 0,
        err_code: 0 } },
  emeter: 
   { realtime: 
      { voltage_mv: 226078,
        current_ma: 279,
        power_mw: 39449,
        total_wh: 60,
        err_code: 0 } },
  schedule: { nextAction: { type: -1, err_code: 0 } } }
------------------------------------------------------------------------

![bildschirmfoto vom 2018-07-03 16-18-32](https://user-images.githubusercontent.com/22934504/42231023-bbf05c3a-7eea-11e8-9bb1-3340e0f9d907.png)

Grüße Pocky :-)

**Comment by Pocky2507** [comment]
Auch noch mit den älteren Steckern die Hardwareversion 1 haben?

**Comment by arteck** [comment]
ich hab mal ein update auf die schnelle gemacht... 
nimm die GIT version und schau mal obs jetzt geht

**Comment by Pocky2507** [comment]
Danke @ arteck 
Das sieht gut aus.
![hs110](https://user-images.githubusercontent.com/22934504/42824296-d789080c-89df-11e8-9133-31b8118a313d.png)
Ich teste das mal weiter mit den Datenpunkten.

**Comment by Pocky2507** [comment]
totalMonthNow bleibt auf 0

**Comment by arteck** [comment]
ich schau mal .. hab mir ne Ver.2.0 Dose besorgt..

**Comment by steviec1211** [comment]
Ich habe auch eine HW2.0 Version. Es werden bei mir werte angezeigt, aber falsche. Ein Bispiel Laut App sind es 1,8 W , der Adapter zeigt mir 60. Schalte ich die Steckdose aus werden immer noch 28 angezeigt. Es werden auch keine Nachkommastellen angezeigt. An & Ausschalten funktioniert.

**Comment by arteck** [comment]
check das jetzt mal

**Comment by steviec1211** [comment]
schaut sehr gut aus. Total Month und Now funktionieren, genau wie auch power. Neu dazugekommen ist die Spannungsanzeige, welche auch funktioniert. Es gibt noch einen Wert current, diesen finde ich in der Kasa App nicht. Für was steht der? Stromstärke aktuell?

Super Arbeit, danke schön.

**Comment by arteck** [comment]
ja das ist der "jetzt" laufende Arbeitswert

**Comment by arteck** [comment]
schein zu laufen ich mach hier zu
