### ISSUE TITLE
Please add to stable repository if shown working for users

### ISSUE THREAD

**Issue by Apollon77** [arteck/ioBroker.hs100#34]

**Comment by foxriver76** [comment]
Push. If you give me your okay, I can add it for you @arteck 

best regards

**Comment by arteck** [comment]
na dann... gib alles:-)

**Comment by foxriver76** [comment]
Welche Version würde sich denn derzeit eignen? ;)

**Comment by arteck** [comment]
nimm die letzte.. hab noch keine neuere
