### ISSUE TITLE
HS110 Hardware Version 3.0 (on Serial) HW 2.0 in adapter not being discovered.

### ISSUE THREAD

**Issue by ramizh** [arteck/ioBroker.hs100#36]
Just moved and havent used ioBroker for a long time. Now that I set everything back, the adapter is unable to find the HS110 Ver 3.0 (or used to be shown as HW-Version 2.0 on the adapter).
Its only able to discover Version 2.0 (1.0 in the adapter).

Any ideas?

Cheers!

**Comment by arteck** [comment]
HS110 Ver 3.0 ???

**Comment by ramizh** [comment]
Sorry for the delayed answer. Yes Hardware 3.0, I bought it in the beginning of the year. In the adapter it used to show it as "2" under version, but on the serial its 3.0. Check this page for datasheet, you can see all 3 versions. Hardware version V2 on serial number shows in the adapter as "1" by the way.

https://www.tp-link.com/de/download/HS110_V3.html

**Comment by arteck** [comment]
check now..i hope ver 3 has same object as ver 2
