### ISSUE TITLE
LB130 Color Support missing

### ISSUE THREAD

**Issue by alexpthe1** [arteck/ioBroker.hs100#38]
LB130 Bulbs are detected and Switching on/off does work, but no parameter for color is available.
It would be great if this would be implemented soon

_thanks in advance_

**Comment by arteck** [comment]
little problem i have no LB130 here

**Comment by alexpthe1** [comment]
i can offer you to do the testing, in current version everything works, just missing the parameter for color.
maybe this links can help you https://www.npmjs.com/package/tplink-lightbulb

**Comment by arteck** [comment]
check https://github.com/arteck/ioBroker.hs100/tree/bulb_color repo

**Comment by alexpthe1** [comment]
Works Great with LB130, thank you a lot!
