### ISSUE TITLE
[v2.0.0] Regelmäßiges Update stoppt nach kurzer Zeit

### ISSUE THREAD

**Issue by Black-Thunder** [arteck/ioBroker.hs100#67]
**Describe the bug**  
Seit dem Update auf v2.0.0 sind zwar bisher keine TCP-Error mehr im Log aufgetaucht, allerdings stoppt jetzt das regelmäßige Update der Steckdosen nach ein paar Minuten. Im Log (auf debug) ist nichts weiter zu sehen, nur das einfach keine Updates mehr erfolgen. Das Intervall ist auf 5 Minuten in den Settings gestellt.

"Verbunden mit hs100" wechselt dann auch von grün auf gelb.

**To Reproduce**  
Einfach Adapter laufen lassen und beobachten, dass 'last-update' nicht mehr aktualisiert wird. Im Log findet auch kein Aktualisierungsversuch mehr statt.

**Expected behavior**  
Regelmäßiges Updaten mit eingestelltem Intervall (wie bei Versionen vor 2.0.0)

**Screenshots & Logfiles**  
[log.txt](https://github.com/arteck/ioBroker.hs100/files/4758108/log.txt)
Auf debug von Start des Adapters bis zum Stopp der Aktualisierung

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 3.1.5
 - Node version: 12.18.0
 - Operating system: Raspberry Pi OS

Eventuell liegt das Problem hier?
https://github.com/arteck/ioBroker.hs100/blob/eff0510f8dc0e9cc8e5974372b9ed1534305b6ab/main.js#L170

Wenn eine Exception auftritt, wird die zwar nun gefangen, aber nie mehr setTimeout aufgerufen. Dadurch bricht das regelmäßige Updaten vermutlich ab, wobei allerdings kein error in meinem Log auftaucht.

**Comment by darkdevil373** [comment]
Das gleiche hier

**Comment by arteck** [comment]
was steht im Log vom iobroker ... wenn der adapter auf gelb geht ??

**Comment by Black-Thunder** [comment]
Raspberry ist per LAN angebunden. Im Log war nichts weiter zu sehen. Bin wieder auf v1.1.6 zurück, da hat alles (abgesehen von den uncaught exceptions) gepasst.

Wenn das aber nur bei mir aufgetreten ist, dann musst da keine Energie für die Ursachensuche investieren. Bin zwischenzeitlich komplett auf ZigBee-Steckdosen umgestiegen, so dass ich den Adapter nicht mehr wirklich verwende, :wink:

**Comment by gedongi** [comment]
Hallo,

ich habe ein ähnliches Problem mit der V2.0.0. Zusätzlich zu den nicht erfolgten Updates kommt hinzu das ich die Steckdosen nicht mehr schalten kann.

Versions:
Adapter version: 2.0.0
JS-Controller version: 3.1.4
Node version: 12.18.0
NPM: 6.14.4
Operating system: Raspbian 9 (stretch)

**Comment by JPfeiffer66** [comment]
Hi!
Gleiches wie hier schon geschrieben. Wird die Instanz neu gestartet, wird LastUpdate einmal kurz aktualisiert. - Danach nicht mehr.
So lässt sich über ioBroker nichts mehr schalten.

**Comment by arteck** [comment]
version 2.0.1
