### ISSUE TITLE
v2.0.0 Warnings/Error when device is unplugged

### ISSUE THREAD

**Issue by vaaarg** [arteck/ioBroker.hs100#68]
Node.js v10.21.0
NPM 6.14.4
jsc 3.1.5

HS100 v2.0.0

instance delete, readd devices or reboot did not help

Log gets spammed with warnings (10 s  interval) when device is offline

`
020-06-11 09:39:00.709 | warn | (1490) getDevice Socket connection Timeout : 192.xxx.xxx.57
`

after restarting the adapter for intervall change following error occurs for the unplugged device

hs100.0 | 2020-06-11 09:44:48.069 | warn | (9639) getDevice Socket connection Timeout : 192xxx.57
-- | -- | -- | --
hs100.0 | 2020-06-11 09:44:44.956 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
hs100.0 | 2020-06-11 09:44:44.956 | error | (9639) [create_state] : connect EHOSTUNREACH 192.xxx.57:9999, stack: Error: connect EHOSTUNREACH 192.xxx.57:9999

**Comment by arteck** [comment]
change the device to off in admin
