### ISSUE TITLE
Steckdosen schalten nicht mehr

### ISSUE THREAD

**Issue by gedongi** [arteck/ioBroker.hs100#69]
**Describe the bug**  
Seit dem Update auf V2.0.0 schalten die Steckdosen nicht mehr und zusätzlich bei den Hs110 werden die Daten nicht mehr aktualisiert.

**To Reproduce**  
Beim restart der Instanz bleibt er auf gelb stehen und wechselt nicht mehr nach grün.

**Expected behavior**  
Sollte wieder normal laufen, daten empfangen und schaltbar sein.

**Screenshots & Logfiles**  
Restart Verhalten der Instanz...
![LOG](https://user-images.githubusercontent.com/37265486/85136078-60816d00-b23f-11ea-8086-9c0764c52c47.png)

**Versions:**  
 Adapter version: 2.0.0
JS-Controller version: 3.1.4
Node version: 12.18.0
NPM: 6.14.4
Operating system: Raspbian 9 (stretch)

**Additional context**  
Muss wieder zurück auf V1.1.6, dann funktioniert wieder alles.

**Comment by TKnpl** [comment]
I noticed that all devices listed in the instance settings must be accessible so that the adapter works correctly. If one device/socket is not in operation, the control of the other devices/sockets only works partially.
Can you fix this?

**Comment by arteck** [comment]
schaue die neue version bitte

**Comment by Kefut** [comment]
Same issue - updated to 2.0.1, but I see hundreds of entries saying "(7764) getDevice Socket connection Timeout ip: "

**Comment by LaplaceII** [comment]
I have the same issues. When I restart the instance it works but data stream stops after a while.

**Comment by arteck** [comment]
fixed
