### ISSUE TITLE
Adapter hängt sich neuerdings öfters auf

### ISSUE THREAD

**Issue by eXTreMe-1337** [arteck/ioBroker.hs100#70]
Seit kurzem hängt sich der Adapter bei mir nach einer Weile immer wieder auf, sprich die werte von meinen HS110 werden nicht mehr aktualisiert. Es könnte evtl mit der aktualisierung auf version 2.0.0 zusammenhängen. Hat sonst noch jemand das gleiche Problem? Ich habe jetzt einen automatischen Adapterneustart alle 12 Std eingestellt und schaue mal ob das mein Problem löst. Das Issue hier erstelle ich in erster linie um zu erfahren ob das Problem noch bei anderen Leuten mit Version 2.0.0 auftritt.
Wenn es etwas gibt wie ich den Fehler genauer analysieren kann bitte Tipps geben. Danke!

**Comment by arteck** [comment]
neue version 2.0.1

**Comment by riedwetter** [comment]
Hallo,
leider besteht das Problem weiterhin, auch mit 2.0.1. Es werden keine neuen Werte mehr hinzugefügt. Bei mir bleibt einfach der Wert stehen und ändert sich nicht mehr.

Die letzte funktionierende Version bei mir ist 1.1.6, dort geht es direkt wieder ohne Änderungen meinerseits. Denke das es bei vielen Probleme gibt.

Kann gerne Logs oder ähnliches bieten.

Mfg

**Comment by 1337gut** [comment]
Kann ich bestätigen. Neue Werte werden nur bei Neustart übertragen, danach nicht mehr.

**Comment by gerbuchner** [comment]
Was mir aufgefallen ist und vlt bei der Fehlersuche hilft...

Mit der 1.1.6 startet die Instanz immer wieder neu, weswegen wohl auch die Daten kommen. Bei der 2.0.1 startet die Instanz nicht mehr neu und die Werte werden nicht mehr aktualisiert.

Wäre schön wenn sich eine Lösung findet ;)

**Comment by arrizer** [comment]
> Kann ich bestätigen. Neue Werte werden nur bei Neustart übertragen, danach nicht mehr.

Hast du im Admin-UI einen Polling-Interval gesetzt? Offenbar wurde der Wert von Millisekunden auf Sekunden geändert (siehe https://github.com/arteck/ioBroker.hs100/blob/22bd0867eb76cc84eec7ba2bca7f7e20854c95a1/main.js#L674)
Hatte das gleiche Problem, musste von 5000 auf 5 umstellen, dann ging alles wieder.

**Comment by eXTreMe-1337** [comment]
> 
> 
> > Kann ich bestätigen. Neue Werte werden nur bei Neustart übertragen, danach nicht mehr.
> 
> Hast du im Admin-UI einen Polling-Interval gesetzt? Offenbar wurde der Wert von Millisekunden auf Sekunden geändert (siehe
> 
> https://github.com/arteck/ioBroker.hs100/blob/22bd0867eb76cc84eec7ba2bca7f7e20854c95a1/main.js#L674
> )
> Hatte das gleiche Problem, musste von 5000 auf 5 umstellen, dann ging alles wieder.

Danke für den Hinweis! Das erklärt so einiges und wird vermutlich die Lösung für das Problem sein!

**Comment by 1337gut** [comment]
Danke, so funktioniert es. Issue kann mMn geschlossen werden.

**Comment by arteck** [comment]
genau so ist es ....

**Comment by Fuxsism** [comment]
@arrizer  @arteck 
sorry das ich das Thema noch einmal auf machen muss... aber ich habe auch das Problem mit dem Adapter.
Ich weiss allerdings nicht wo ich diesen Wert ändern kann, ich bin noch ganz neu beim IoBroker...

Wo finde ich also die entsprechende Zeile zum Ändern??
Würd mich über Hilfe sehr freuen...

**Comment by mrbungle64** [comment]
> Wo finde ich also die entsprechende Zeile zum Ändern??
> Würd mich über Hilfe sehr freuen...

@Fuxsism 
In den Adapter Einstellungen unter "Haupteinstellungen" => "Abfrage Intervall[sec]"
