### ISSUE TITLE
Wrong type for the objects

### ISSUE THREAD

**Issue by Obsthaendler** [arteck/ioBroker.hs100#71]
Hello,

the objects have the wrong types, so nothing can be calculated for energy.
What is the reason, that numbers have a string as type?

                  this.extendObjectAsync(`${ip_state}.power`, {
                      type: 'state',
                      common: {
                          name: hs_name || ip,
                          type: '**string**',
                          read: true,
                          write: false,
                          def: 0,
                          role: 'value',
                          desc: 'power value'
                      },
                      native: {},
                  });

The other objects have the same issue, so the Adapter e.g. SourceAnalytix can't calculated.

Best regards

**Comment by IO-Link** [comment]
Same question here - my scripts doesn't work anymore...

**Comment by Obsthaendler** [comment]
Who can fixed it?

**Comment by arteck** [comment]
check https://github.com/arteck/ioBroker.hs100/tarball/strToNum

**Comment by weindler** [comment]
Habe das selbe Problem, bitte beheben, diese Objekte sollten als nummer angelegt werden.

**Comment by arteck** [comment]
fixed
