### ISSUE TITLE
Keine Messungen bei hs100 mit aktueller Firmware?

### ISSUE THREAD

**Issue by Michaelnorge** [arteck/ioBroker.hs100#74]
Ich habe seit einem Jahr zwei hs110 eingebunden, die einwandfrei funktionieren.
Zwecks Erweiterung meines Smarthome habe ich mir eine neue Steckdose, allerdings eine HS100, zugelegt.
Beim Einbinden ins WLAN mittels KASA gab es auch prompt ein Update auf die Steckdose, sie läuft jetzt mit der Version 1.1.1 Build 191209 Rel.093031.

Die Steckdose kann allerdings in den Objekten lediglich geschaltet werden, es gibt keine Strommessungen.

Kann das jemand bestätigen?
![hs100](https://user-images.githubusercontent.com/42386692/91190564-02b44a00-e6f4-11ea-8dc2-e0575ed9eea1.jpg)

**Comment by Pocky2507** [comment]
HS110 ist MIT Strommessung
HS100 ist OHNE Strommessung

**Comment by Michaelnorge** [comment]
Verdammt, da scheine ich was verwechselt zu haben!!
Sorry!!!
