### ISSUE TITLE
Feature Request KL60 Brightness

### ISSUE THREAD

**Issue by PauleBertt** [arteck/ioBroker.hs100#75]
Hi 

Würde gerne meine KL60 hinzufügen doch das Feld für Helligkeit fehlt.

Was für Schritte muss ich ungefähr machen damit ich das zum Projekt hinzufügen kann?

Mit freundlichen Grüßen

Paul

**Comment by PauleBertt** [comment]
wäre das ausreichend?
kann irgendwie das repo nicht so in mein ioBroker laden
https://github.com/PauleBertt/ioBroker.hs100/commit/2a1496395c672bf5d86adba26013084fa99e35f7

**Comment by arteck** [comment]
thx merged
