### ISSUE TITLE
Update js-controllers V 3.3.1 Warnmeldungen

### ISSUE THREAD

**Issue by sigi2345** [arteck/ioBroker.hs100#89]
Hallo,

nach einen Update des js-controllers auf V 3.3.1 kommen folgende Warnmeldungen:

`

hs100.0 | 2021-04-30 06:49:45.021 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
-- | -- | -- | --
hs100.0 | 2021-04-30 06:49:44.622 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:49:14.830 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:49:14.438 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:48:44.614 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:48:44.215 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:48:14.426 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:48:14.040 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:47:44.210 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:47:43.811 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:47:14.021 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:47:13.627 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:46:43.828 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:46:43.435 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:46:13.617 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:46:13.189 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:45:43.400 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:45:43.008 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:45:13.186 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:45:12.802 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:44:42.994 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:44:42.595 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:44:12.792 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:44:12.394 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:43:42.592 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:43:42.205 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:43:12.403 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:43:12.016 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:42:42.215 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:42:41.817 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:42:11.999 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:42:11.597 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:41:41.809 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:41:41.423 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:41:11.584 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:41:11.197 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:40:41.371 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:40:40.966 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:40:11.189 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:40:10.786 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:39:40.971 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:39:40.570 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:39:10.782 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:39:10.390 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:38:40.582 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:38:40.191 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:38:10.378 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:38:09.977 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:37:40.185 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:37:39.794 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:37:09.974 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:37:09.583 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:36:39.763 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:36:39.355 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:36:09.571 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:36:09.179 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:35:39.367 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:35:38.974 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:35:09.178 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:35:08.776 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:34:38.977 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:34:38.573 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:34:08.787 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:34:08.398 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:33:38.589 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:33:38.189 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:33:08.372 | warn | (9752) State value to set for "hs100.0.192_168_178_23.ledState" has wrong type "boolean" but has to be "string"
hs100.0 | 2021-04-30 06:33:07.978 | warn | (9752) State value to set for "hs100.0.192_168_178_28.ledState" has wrong type "boolean" but has to be "string"

`

**Comment by arteck** [comment]
installiere neue Version

**Comment by sigi2345** [comment]
![Screenshot (3726)](https://user-images.githubusercontent.com/41079106/116653553-b9558200-a987-11eb-9016-c93847bae49e.png)
