### ISSUE TITLE
Wrong unit for current

### ISSUE THREAD

**Issue by KenADev** [arteck/ioBroker.hs100#93]
**Describe the bug**  
The unit for the current is shown "A", but it should be "mA".  

Example from the adapter output: 230V @ 7W=> shown as 30**A**  
This is incorrect.   
Correct is: 7W / 230V = 0.030 A = 30**mA**

**Versions:**  
 - Adapter version: 2.0.3

**Comment by KenADev** [comment]
Another remark: Just the unit should be changed, changing the value to 0.030 would possibly break dependend systems (grafana graphs, calculations, ...)

**Comment by arteck** [comment]
check now plz
