### ISSUE TITLE
KP115 keine Verbrauchswerte

### ISSUE THREAD

**Issue by gerbuchner** [arteck/ioBroker.hs100#94]
Hallo,

hatte bisher die hs110. Da es diese so gut wie nicht mehr gibt und der Nachfolger die kp115 sein soll, habe ich mir davon eine bestellt. Die kp115 wird vom Adapter erkannt und ich kann sie auch ein bzw. aus schalten aber die Verbrauchsanzeige fehlt. Es werden die Datenpunkte dafür gar nicht erst angelegt.

Wäre super wenn diese mit eingebunden werden könnten.

Vielen Dank im Voraus

**Comment by gerbuchner** [comment]
Ich hab gerade bei mir lokal eine Erweiterung eingebaut die funktioniert.

Am besten mit "suchen/ersetzen" über die main.js gehen.
Suchen: hs_model.search(/110/i) != -1
Ersetzen: hs_model.search(/110/i) != -1 || hs_model.search(/115/i) != -1

Wäre super wenn das den Weg in den Adapter schafft. Bin mit Git und einem eigene Branch nicht wirklich vertraut.

**Comment by arteck** [comment]
dann schau mal.. ich habs eben korrigiert

**Comment by gerbuchner** [comment]
Funktioniert. Vielen Dank fürs einbauen!
