### ISSUE TITLE
Switch state is not correct in ioBroker

### ISSUE THREAD

**Issue by Starter4711** [arteck/ioBroker.hs100#98]
Hello,

HS100 inserted in APP, works fine. Is conntected to Wifi, via App switchable.
IP Adress entered in the ioBroker Adapter.
Objects shown with all informations (HW-Vers 4.0, HS100(EU), all is filled with data)
Switch does always show "false", but switched (true). 
I have 3 HS100 and only 1 does not show the switch correctly, other work fine.
Tried several versions of the adapter, all the same.

3.2.16/v12.22.1/runs on synology vmm with 8GB Ram and enough hard drive space

THX

(Humidor-Dehumidifier, 192.168.0.191)
<img width="1229" alt="Bildschirmfoto 2021-07-29 um 17 46 11" src="https://user-images.githubusercontent.com/15359915/127523477-523b3148-6589-4139-b2bb-dfafc6388524.png">
![IMG_20210729_174515](https://user-images.githubusercontent.com/15359915/127523523-c4c8ca6f-06b9-456e-af60-330ee01cd67d.PNG)

**Comment by arteck** [comment]
your poll intervall is ??
