### ISSUE TITLE
No Update from 2.03 to 2.06 is possible.

### ISSUE THREAD

**Issue by weindler** [arteck/ioBroker.hs100#99]
Here is the log
`
<html><body>

host.raspberrypi | 2021-08-02 16:44:23.443 | info | iobroker upload [0] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/admin.d.ts admin.d.ts video/mp2t
-- | -- | -- | --
host.raspberrypi | 2021-08-02 16:44:23.373 | info | iobroker upload [1] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/custom_m.html custom_m.html text/html
host.raspberrypi | 2021-08-02 16:44:23.314 | info | iobroker upload [2] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/hs100.png hs100.png image/png
host.raspberrypi | 2021-08-02 16:44:23.256 | info | iobroker upload [3] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/index.html index.html text/html
host.raspberrypi | 2021-08-02 16:44:23.199 | info | iobroker upload [4] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/index_m.html index_m.html text/html
host.raspberrypi | 2021-08-02 16:44:23.139 | info | iobroker upload [5] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/style.css style.css text/css
host.raspberrypi | 2021-08-02 16:44:22.954 | info | iobroker upload [6] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/words.js words.js application/javascript
host.raspberrypi | 2021-08-02 16:44:22.897 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR!      /home/iobroker/.npm/_logs/2021-08-02T14_44_22_890Z-debug.log
host.raspberrypi | 2021-08-02 16:44:22.896 | info | iobroker
host.raspberrypi | 2021-08-02 16:44:22.885 | info | iobroker npm ERR! notarget In most cases you or one of your  dependencies are requestingnpm ERR! notarget a package version that  doesn't exist.
host.raspberrypi | 2021-08-02 16:44:22.884 | info | iobroker npm ERR! notarget No matching version found for iobroker.hs100@2.0.6.
host.raspberrypi | 2021-08-02 16:44:22.866 | info | iobroker npm ERR! code ETARGET
host.raspberrypi | 2021-08-02 16:44:08.001 | info | iobroker npm install iobroker.hs100@2.0.6 --loglevel error --prefix "/opt/iobroker" (System call)
host.raspberrypi | 2021-08-02 16:44:07.998 | info | iobroker NPM version: 6.14.13
host.raspberrypi | 2021-08-02 16:44:07.392 | info | iobroker Update hs100 from @2.0.3 to @2.0.6
host.raspberrypi | 2021-08-02 16:44:04.849 | info | iobroker upgrade hs100

</body>
</html>`

Node.js
    v12.22.2 
NPM
    6.14.13

**Comment by fornax76-git** [comment]
Same issue here.

No update from 2.0.3 to 2.0.6 possible.
Update to 2.0.5 (Beta) works.
Update from 2.0.5 ti 2.0.6 doesn't work.

Seems to me that the version doesn't exist.

`$ ./iobroker upgrade hs100
Update hs100 from @2.0.5 to @2.0.6
NPM version: 6.14.14
npm install iobroker.hs100@2.0.6 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.hs100@2.0.6.
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-08-05T07_02_22_004Z-debug.log
upload [5] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/words.js words.js application/javascript
upload [4] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/style.css style.css text/css
upload [3] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/index_m.html index_m.html text/html
upload [2] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/index.html index.html text/html
upload [1] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/hs100.png hs100.png image/png
upload [0] hs100.admin /opt/iobroker/node_modules/iobroker.hs100/admin/admin.d.ts admin.d.ts video/mp2t
Adapter "hs100" updated
process exited with code 0`

**Comment by arteck** [comment]
fixed
